[package]
name = "philpsx_basic_bin"
version = "0.1.0"
edition = "2024"
authors = [
    "Phillip Potter <phil@philpotter.co.uk>"
]

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
philpsx_core = { path = "../philpsx_core" }